### ISSUE TITLE
Detected as virus

### ISSUE THREAD

**Issue by rexsllemel** [Kintoyyy/AZK-Manager#5]
Anti Virus prompt and detected as Trojan. How?

**Comment by Kintoyyy** [comment]
hello @rexsllemel , Can you provide more information and a screenshot of the file that was flagged as a virus.

**Comment by rexsllemel** [comment]
> hello @rexsllemel , Can you provide more information and a screenshot of the file that was flagged as a virus.

This is my third time downloading as ZIP. I can ignore though but I was wondering.

![image](https://github.com/Kintoyyy/AZK-Manager/assets/15032596/6229b55c-4e9f-4ae0-be0f-219a58a655d9)

edit:
It works okay using git clone

**Comment by Kintoyyy** [comment]
> > hello @rexsllemel , Can you provide more information and a screenshot of the file that was flagged as a virus.
> 
> This is my third time downloading as ZIP. I can ignore though but I was wondering.
> 
> ![image](https://github.com/Kintoyyy/AZK-Manager/assets/15032596/6229b55c-4e9f-4ae0-be0f-219a58a655d9)
> 
> edit:
> It works okay using git clone

It seems that you are using a download manager; perhaps your download manager is causing the false positive. Try downloading the zip file directly from Github.

**Comment by rexsllemel** [comment]
There is no problem while downloading from browser without using download manager. This should be false positive. Thanks!
