### ISSUE TITLE
Desktop app not accessible outside the local network

### ISSUE THREAD

**Issue by rexsllemel** [Kintoyyy/AZK-Manager#7]
When using the desktop app, the ip is 127.0.0.1 with corresponding port and can be accessed on localhost. However, even with disabling the firewall, the assigned ip address to the pc where the app was running, it can't be access trough the lan connection.

There was no firewall problem cuz the firewall was disabled and can be assured that the port is accessible by running xammp.

**Comment by Kintoyyy** [comment]
Hi @rexsllemel, The desktop app is only design tobe used within the pc its running at if you want it tobe locally accessable in your try to host it in xamp and use the IP address of your PC or host it on an orangePi/RasPi connected to your network
